name: Brian AI Daily Briefing

# 1. 언제 실행할까요? (Trigger)
on:
  schedule:
    # 매일 한국 시간 아침 8시 (UTC 23시)
    # 분 시 일 월 요일 (UTC 기준)
    - cron: '0 23 * * *'
  
  # 수동으로 실행 버튼 만들기 (테스트용)
  workflow_dispatch:

# 2. 무슨 작업을 할까요? (Jobs)
jobs:
  run-news-bot:
    runs-on: ubuntu-latest # 리눅스 가상 PC 임대

    steps:
    # (1) 코드 가져오기
    - name: Checkout repository
      uses: actions/checkout@v4

    # (2) 파이썬 3.11 설치
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # (3) 라이브러리 설치
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # (4) 봇 실행 (비밀번호 주입)
    - name: Run Brian AI Bot
      env:
        # GitHub Settings에 등록한 비밀값들을 환경변수로 연결
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python bot.py